# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-37fec7a5-f605-4de8-9a93-f8effae45a15";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-37fec7a5-f605-4de8-9a93-f8effae45a15".device = "/dev/disk/by-uuid/37fec7a5-f605-4de8-9a93-f8effae45a15";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/538D-D7BC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a04f8608-37d9-4eb7-865e-b86afbbb6762"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
