# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-507f984d-5d52-4507-8640-3e3f5fe3d60e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-507f984d-5d52-4507-8640-3e3f5fe3d60e".device = "/dev/disk/by-uuid/507f984d-5d52-4507-8640-3e3f5fe3d60e";

  fileSystems."/bin" =
    { device = "/usr/bin";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D1CD-9F14";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/data_hdd_1" =
    { device = "/dev/disk/by-uuid/2dab76d4-4e7f-4b82-9e69-7eebac01064c";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-902098a8-3c57-4f21-b4d9-f1af4be9dc80"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
